// The 100 accounts of the App Store review environment.
//
// Everything a reviewer can read is in here and it is all English: the name,
// the bio, the circles. Every profile answers every field the card can show --
// height, smoking, family and kids -- with deliberate spread, so a reviewer
// paging through cards sees the whole vocabulary of the product rather than
// one repeated shape.
//
// `at` picks a point from PLACES: a residential one for somebody at home, an
// office park for somebody at work. Coordinates are jittered per account.

export const PLACES = {
  // homes
  cupertino:     [37.3230, -122.0322],
  sunnyvale:     [37.3688, -122.0363],
  santaclara:    [37.3541, -121.9552],
  willowglen:    [37.3050, -121.8996],
  mountainview:  [37.3861, -122.0839],
  paloalto:      [37.4419, -122.1430],
  menlopark:     [37.4530, -122.1817],
  redwoodcity:   [37.4852, -122.2364],
  sanmateo:      [37.5630, -122.3255],
  noevalley:     [37.7509, -122.4331],
  mission:       [37.7599, -122.4148],
  sunset:        [37.7599, -122.4948],
  oakland:       [37.8044, -122.2712],
  berkeley:      [37.8715, -122.2730],
  alameda:       [37.7652, -122.2416],
  fremont:       [37.5485, -121.9886],
  losgatos:      [37.2358, -121.9624],
  campbell:      [37.2872, -121.9500],
  milpitas:      [37.4323, -121.8996],
  fostercity:    [37.5585, -122.2711],
  // offices
  applepark:     [37.3349, -122.0090],
  googleplex:    [37.4220, -122.0841],
  researchpark:  [37.4090, -122.1520],
  moffett:       [37.4050, -122.0250],
  soma:          [37.7820, -122.3960],
  findistrict:   [37.7940, -122.3990],
  downtownsj:    [37.3350, -121.8900],
  citycenter:    [37.8040, -122.2720],
  missionbay:    [37.7680, -122.3930],
  redwoodshores: [37.5330, -122.2510],
}

export const OFFICES = new Set([
  'applepark', 'googleplex', 'researchpark', 'moffett', 'soma',
  'findistrict', 'downtownsj', 'citycenter', 'missionbay', 'redwoodshores',
])

// ── circles ────────────────────────────────────────────────────────────────
// kind: 'open' (anyone joins), 'approval' (a manager lets you in),
// 'private' (invite link only, invisible to search).
export const CIRCLES = [
  { key: 'trailrunners', name: 'Bay Area Trail Runners', kind: 'open', link: 'https://www.strava.com/clubs/bay-area-trail-runners',
    desc: 'We run the ridge trails above the peninsula every Saturday at 7am and one weekday evening. All paces welcome, nobody is left behind at the trailhead.' },
  { key: 'neighbors', name: 'Cupertino Neighbors', kind: 'approval', link: 'https://nextdoor.com/city/cupertino--ca',
    desc: 'Neighbours around Stevens Creek and Blaney. We share local recommendations, tool lending, block parties and the occasional lost cat.' },
  { key: 'farmers', name: 'Sunday Farmers Market Crew', kind: 'open', link: 'https://www.cafarmersmkts.com',
    desc: 'We meet at the Mountain View market every Sunday morning, walk the stalls together and cook whatever looked best that week.' },
  { key: 'boardgames', name: 'South Bay Board Games', kind: 'open', link: 'https://www.meetup.com/south-bay-board-games',
    desc: 'Weekly game nights in Campbell and Sunnyvale. Heavy euros early, party games late, and a shelf of rules lawyers who are happy to teach.' },
  { key: 'cycling', name: 'Peninsula Cycling Club', kind: 'approval', link: 'https://www.strava.com/clubs/peninsula-cycling',
    desc: 'Road rides from Palo Alto over Old La Honda and down to the coast. Two groups by pace, a coffee stop that is never optional.' },
  { key: 'alumni', name: 'Stanford Alumni in the Bay', kind: 'approval', link: 'https://alumni.stanford.edu',
    desc: 'Graduates living between San Jose and the city. Talks, dinners and a mentoring thread for people changing field.' },
  { key: 'film', name: 'SF Film Club', kind: 'open', link: 'https://www.meetup.com/sf-film-club',
    desc: 'One film a week at the Roxie or the Balboa, drinks afterwards to argue about it. Repertory programming, no blockbusters.' },
  { key: 'swimmers', name: 'Bay Swimmers', kind: 'approval', link: 'https://www.dolphinclub.org',
    desc: 'Open water swimming at Aquatic Park year round, no wetsuit needed but nobody will judge you. Dawn swims Tuesday and Friday.' },
  { key: 'climbing', name: 'Weekday Climbers', kind: 'open', link: 'https://touchstoneclimbing.com',
    desc: 'Indoor sessions after work at Sunnyvale and Belmont, outdoor trips to Castle Rock when the weather holds. Belay partners always available.' },
  { key: 'vinyl', name: 'Bay Area Vinyl Collectors', kind: 'open', link: 'https://www.discogs.com',
    desc: 'Record swaps, listening evenings and trips to the shops on Telegraph. Bring one record you love and one you are ready to part with.' },
  { key: 'newparents', name: 'New Parents of Mountain View', kind: 'approval', link: 'https://www.meetup.com/mountain-view-new-parents',
    desc: 'Parents of children under four. Playground mornings, hand me down clothes, and honest conversation about how hard the first year is.' },
  { key: 'founders', name: 'Startup Founders Coffee', kind: 'approval', link: 'https://www.meetup.com/bay-area-founders-coffee',
    desc: 'Early stage founders meeting for coffee on Wednesdays in SoMa. No pitching, no investors in the room, just the problems of the week.' },
  { key: 'photowalks', name: 'Silicon Valley Photo Walks', kind: 'open', link: 'https://www.flickr.com/groups',
    desc: 'A different neighbourhood every second Sunday, cameras of any kind. We finish with a print review over lunch once a month.' },
  { key: 'wine', name: 'Napa Weekend Tasting', kind: 'approval', link: 'https://www.napavintners.com',
    desc: 'A carpool up to the valley once a month, three or four small producers a day, and a shared spreadsheet of everything we liked.' },
  { key: 'garden', name: 'Palo Alto Community Garden', kind: 'approval', link: 'https://www.cityofpaloalto.org',
    desc: 'Plot holders and volunteers at the Eleanor Pardee garden. Seed swaps in spring, tomato surplus in August, compost duty all year.' },
  { key: 'volunteers', name: 'Bay Area Volunteers', kind: 'open', link: 'https://www.volunteermatch.org',
    desc: 'Weekend shifts at food banks, beach cleanups and the winter shelter. Sign up for what you can, nobody keeps score.' },
  { key: 'yoga', name: 'Sunset Yoga at Baylands', kind: 'open', link: 'https://www.baylandsyoga.com',
    desc: 'Outdoor practice at the Palo Alto baylands on Tuesday and Thursday evenings, donation based, mats to borrow if you forget yours.' },
  { key: 'jazz', name: 'Jazz Nights SF', kind: 'open', link: 'https://www.sfjazz.org',
    desc: 'Small group jazz in the Fillmore and the Mission, two or three nights a month. Tickets bought together, table shared.' },
  { key: 'bookclub', name: 'Berkeley Book Club', kind: 'approval', link: 'https://www.pegasusbookstore.com',
    desc: 'One novel a month, discussed properly over two hours in a back room on Shattuck. Fiction in translation about half the time.' },
  { key: 'marin', name: 'Weekend Hikers of Marin', kind: 'private', link: 'https://www.nps.gov/goga',
    desc: 'A small group that hikes Tam, Point Reyes and the Marin headlands most weekends. Invite only so the trailhead parking stays sane.' },
  { key: 'surf', name: 'Pacifica Surf Mornings', kind: 'open', link: 'https://www.surfline.com',
    desc: 'Dawn patrol at Linda Mar before work. Beginners welcome, there is always a spare board and someone to read the tide chart for you.' },
  { key: 'chess', name: 'Mechanics Chess Nights', kind: 'open', link: 'https://www.chessclub.org',
    desc: 'Casual and rated games downtown on Tuesday evenings, plus a blitz table that runs until they close the building.' },
]

// ── people ─────────────────────────────────────────────────────────────────
// kids: array of ages (empty array = no kids). wants: wants (more) kids.
const P = (name, male, age, at, height, smokes, kids, wants, bio, circles) =>
  ({ name, male, age, at, height, smokes, kids, wants, bio, circles })

export const PEOPLE = [
  P('Maya', false, 31, 'mountainview', 168, false, [], true, 'Product designer at a small hardware company. I run the Baylands loop most evenings, keep a plot at the community garden, and I am the person who brings the good tomatoes to a potluck.', ['trailrunners', 'garden', 'yoga']),
  P('Daniel', true, 36, 'applepark', 182, false, [4], false, 'Backend engineer, father to a four year old who thinks my job is fixing the wifi. Weekends are the playground, the farmers market and one long ride if I can escape.', ['newparents', 'cycling', 'farmers']),
  P('Priya', false, 29, 'sunnyvale', 160, false, [], true, 'Data scientist by day, climbing three evenings a week. I read two novels a month and will happily tell you about both of them.', ['climbing', 'bookclub', 'trailrunners']),
  P('Marcus', true, 42, 'oakland', 190, true, [11, 8], false, 'Carpenter with a shop in West Oakland. Two kids, one dog, a record collection that has outgrown the wall. Cigarettes only when I am working late.', ['vinyl', 'jazz', 'volunteers']),
  P('Elena', false, 34, 'noevalley', 165, false, [], true, 'Emergency room nurse. I swim at Aquatic Park before shifts and I am at the Roxie most Thursdays, usually for something with subtitles.', ['swimmers', 'film', 'volunteers']),
  P('Tom', true, 45, 'redwoodcity', 178, false, [16], false, 'Structural engineer, teenage daughter, weekend cyclist. I have opinions about bridges and I will share them if you let me.', ['cycling', 'alumni', 'boardgames']),
  P('Aisha', false, 27, 'berkeley', 172, false, [], true, 'Graduate student in urban planning. I photograph the same three streets over and over and I run a book club that argues too much.', ['photowalks', 'bookclub', 'volunteers']),
  P('Jonah', true, 33, 'soma', 175, true, [], true, 'Founder of a two person company, which mostly means I do support at midnight. Jazz clubs and long walks are how I stop thinking about it.', ['founders', 'jazz', 'photowalks']),
  P('Clara', false, 39, 'paloalto', 158, false, [7, 3], false, 'Pediatrician, mother of two, cook of increasingly ambitious Sunday dinners. I trade seedlings with half the garden.', ['newparents', 'garden', 'farmers']),
  P('Victor', true, 51, 'losgatos', 185, false, [22, 19], false, 'Winemaker turned consultant. My children are grown and I have finally taken up surfing, badly, at an age that surprises everyone.', ['wine', 'surf', 'cycling']),
  P('Nina', false, 25, 'mission', 163, true, [], true, 'Line cook working my way up. Days off are the market, a used record shop and whatever film is showing at the Balboa.', ['farmers', 'vinyl', 'film']),
  P('Owen', true, 30, 'googleplex', 180, false, [], true, 'Machine learning engineer. Trail running in the hills before work, board games with the same six people every Wednesday.', ['trailrunners', 'boardgames', 'climbing']),
  P('Sofia', false, 44, 'sanmateo', 170, false, [14, 12], true, 'High school chemistry teacher. Two kids, a garden that is mostly weeds, and a standing Sunday swim I refuse to miss.', ['swimmers', 'garden', 'volunteers']),
  P('Ravi', true, 38, 'santaclara', 176, false, [5], false, 'Hardware reliability engineer. My son and I ride the creek trail every Saturday, and I still play chess badly on Tuesday nights.', ['chess', 'cycling', 'newparents']),
  P('Grace', false, 47, 'berkeley', 167, false, [], false, 'Librarian. I run the book club, volunteer at the food bank, and I have walked every trail in Marin at least twice.', ['bookclub', 'volunteers', 'marin']),
  P('Leo', true, 26, 'downtownsj', 174, true, [], true, 'Sound engineer at a small venue. If there is live jazz within twenty miles I probably know who is playing.', ['jazz', 'vinyl', 'film']),
  P('Hannah', false, 35, 'missionbay', 162, false, [], true, 'Biotech researcher. Open water swimmer, terrible surfer, and the person who organises the lab potluck.', ['swimmers', 'surf', 'volunteers']),
  P('Andre', true, 49, 'alameda', 188, false, [20], false, 'Union electrician. One grown son, a garage full of records and a bicycle older than he is.', ['vinyl', 'cycling', 'volunteers']),
  P('Julia', false, 32, 'campbell', 155, false, [], true, 'Veterinarian. Board games, long hikes, and a small dog with opinions. I bring snacks to everything.', ['boardgames', 'marin', 'trailrunners']),
  P('Ben', true, 41, 'moffett', 183, false, [9, 6], false, 'Aerospace engineer, two kids who build better rockets than I did at their age. Camping most long weekends.', ['newparents', 'marin', 'boardgames']),
  P('Rosa', false, 28, 'fremont', 166, false, [], true, 'Physical therapist. Yoga at the baylands, climbing on Wednesdays, and a slow project restoring my grandmother’s recipes.', ['yoga', 'climbing', 'farmers']),
  P('Chris', true, 55, 'findistrict', 179, true, [26, 24], false, 'Corporate lawyer counting the years to retirement. Wine trips, jazz clubs, and a plan to walk the coast path end to end.', ['wine', 'jazz', 'alumni']),
  P('Yuki', false, 30, 'sunnyvale', 159, false, [], true, 'Front end developer. I photograph the valley on weekends and I am learning to surf at an embarrassing pace.', ['photowalks', 'surf', 'boardgames']),
  P('Samuel', true, 34, 'oakland', 187, false, [], true, 'Chef. Twelve hour days, one day off, and I spend it at the market talking to the people who grew everything.', ['farmers', 'volunteers', 'vinyl']),
  P('Isabel', false, 52, 'menlopark', 164, false, [23, 21], false, 'Architect. Empty nest, a new road bike, and the garden I finally have time for.', ['cycling', 'garden', 'alumni']),
  P('Felix', true, 29, 'mission', 177, true, [], true, 'Barista and part time photographer. My camera is always in the bag and my film budget is out of control.', ['photowalks', 'film', 'jazz']),
  P('Amara', false, 37, 'citycenter', 171, false, [8], true, 'City planner. My daughter comes to the beach cleanups with me and complains the entire time, which I count as parenting.', ['volunteers', 'newparents', 'swimmers']),
  P('Peter', true, 60, 'paloalto', 181, false, [30, 27], false, 'Retired professor. Chess on Tuesdays, hiking on Saturdays, and a stack of novels I keep meaning to finish.', ['chess', 'marin', 'bookclub']),
  P('Layla', false, 26, 'willowglen', 169, false, [], true, 'Nurse practitioner in training. Trail runs before class, board games after, and very little sleep in between.', ['trailrunners', 'boardgames', 'yoga']),
  P('Nathan', true, 43, 'researchpark', 184, false, [13], false, 'Patent attorney and weekend climber. My son belays better than most adults I know.', ['climbing', 'alumni', 'marin']),
  P('Mei', false, 33, 'fostercity', 157, false, [], false, 'Financial analyst. I swim year round, I keep a plot at the garden, and I do not believe in the concept of a lazy Sunday.', ['swimmers', 'garden', 'cycling']),
  P('Gabriel', true, 31, 'soma', 173, false, [], true, 'Product manager at a startup that may or may not exist next year. Founders coffee keeps me sane.', ['founders', 'film', 'climbing']),
  P('Dana', false, 46, 'sunset', 168, true, [17, 15], false, 'Graphic designer. Two teenagers, one very old cat, and a vinyl habit I refuse to apologise for.', ['vinyl', 'film', 'photowalks']),
  P('Ethan', true, 27, 'milpitas', 186, false, [], true, 'Test engineer. Surfing before work when the swell is right, chess when it is not.', ['surf', 'chess', 'boardgames']),
  P('Naomi', false, 40, 'redwoodshores', 161, false, [10, 7], true, 'Database engineer, mother of two, and the person who books the campsite six months ahead.', ['newparents', 'marin', 'garden']),
  P('Ali', true, 35, 'sanmateo', 178, true, [], true, 'Restaurant supplier. I know every market in the bay and I will argue about stone fruit with anybody.', ['farmers', 'wine', 'jazz']),
  P('Tessa', false, 24, 'berkeley', 173, false, [], true, 'Environmental science student. Beach cleanups, bike commuting, and a genuinely alarming amount of coffee.', ['volunteers', 'cycling', 'bookclub']),
  P('Hugo', true, 48, 'losgatos', 180, false, [18, 16], false, 'Orthopaedic surgeon. Cycling is my therapy and my knees have not forgiven me for the running years.', ['cycling', 'wine', 'alumni']),
  P('Camille', false, 36, 'noevalley', 165, false, [], true, 'Documentary editor. Film club regular, ocean swimmer, and I still write letters on paper.', ['film', 'swimmers', 'jazz']),
  P('Ivan', true, 53, 'oakland', 189, true, [28], false, 'Jazz drummer and music teacher. Thirty years in the same city and I still find new rooms to play in.', ['jazz', 'vinyl', 'volunteers']),
  P('Simone', false, 29, 'mountainview', 156, false, [], true, 'UX researcher. Yoga most evenings, photo walks most Sundays, and a standing reservation for the market on Saturday.', ['yoga', 'photowalks', 'farmers']),
  P('Robert', true, 39, 'googleplex', 182, false, [6, 2], false, 'Site reliability engineer. Two small children, a very patient partner in the past tense, and a bicycle I ride at 5am because it is the only quiet hour.', ['newparents', 'cycling', 'trailrunners']),
  P('Farida', false, 42, 'santaclara', 170, false, [12], true, 'Radiologist. My daughter and I hike Marin most weekends and argue about which trail is best.', ['marin', 'bookclub', 'swimmers']),
  P('Jack', true, 32, 'moffett', 176, false, [], true, 'Flight test engineer. Climbing partner wanted, board game group already full.', ['climbing', 'boardgames', 'trailrunners']),
  P('Lucia', false, 50, 'paloalto', 163, false, [24, 20], false, 'Small business owner, two grown children. Wine weekends and a garden plot that is finally under control.', ['wine', 'garden', 'volunteers']),
  P('Aaron', true, 25, 'mission', 175, true, [], true, 'Bike messenger and part time student. I have been to every record shop in this city more than once.', ['vinyl', 'cycling', 'photowalks']),
  P('Ingrid', false, 45, 'menlopark', 174, false, [19], false, 'Molecular biologist. Long distance swimmer, slow reader, and the mother of a teenager who is better at chess than I am.', ['swimmers', 'chess', 'bookclub']),
  P('Diego', true, 37, 'downtownsj', 179, false, [9], false, 'Firefighter. Trail running and surfing on the days I am not on shift, and a son who wants to do both.', ['trailrunners', 'surf', 'volunteers']),
  P('Beatrice', false, 58, 'berkeley', 160, false, [32, 29], false, 'Retired teacher. I run the book club, I feed the neighbours, and I still take the early swim.', ['bookclub', 'swimmers', 'neighbors']),
  P('Karl', true, 44, 'cupertino', 185, false, [15, 11], false, 'Semiconductor engineer. Neighbourhood block party organiser, reluctantly, for the third year running.', ['neighbors', 'boardgames', 'newparents']),
  P('Anya', false, 31, 'redwoodcity', 167, false, [], true, 'Landscape architect. Garden plot, camera bag, and a weakness for a long drive up the coast.', ['garden', 'photowalks', 'marin']),
  P('Miles', true, 28, 'soma', 181, false, [], true, 'Designer at an agency. Film club, jazz nights, and a growing pile of unfinished side projects.', ['film', 'jazz', 'founders']),
  P('Ruth', false, 54, 'sanmateo', 162, true, [26], false, 'Hospice nurse. Twenty six years of it. Gardening and long walks are how I put the day down.', ['garden', 'volunteers', 'marin']),
  P('Emil', true, 33, 'sunnyvale', 177, false, [], true, 'Robotics engineer. Chess club, climbing gym, and an ongoing argument with my landlord about the balcony.', ['chess', 'climbing', 'boardgames']),
  P('Talia', false, 38, 'missionbay', 169, false, [4], true, 'Clinical trials manager. New to the city with a toddler, looking for people who understand both halves of that sentence.', ['newparents', 'yoga', 'volunteers']),
  P('Gregor', true, 46, 'findistrict', 183, true, [21, 18], false, 'Investment analyst. Wine, jazz and one very steep bike ride every Sunday to make up for both.', ['wine', 'jazz', 'cycling']),
  P('Paloma', false, 27, 'alameda', 158, false, [], true, 'Marine biologist. If I am not in the water I am probably talking about it.', ['swimmers', 'surf', 'volunteers']),
  P('Adrian', true, 40, 'researchpark', 178, false, [10, 8], false, 'Physicist. Two kids who ask better questions than my students. Weekend hiker, weekday cyclist.', ['marin', 'cycling', 'alumni']),
  P('Bianca', false, 35, 'campbell', 171, false, [], false, 'Pastry chef. Early mornings mean early nights, so my social life is entirely daylight hours.', ['farmers', 'photowalks', 'yoga']),
  P('Nils', true, 52, 'fremont', 186, false, [25, 22], false, 'Mechanical engineer. Restoring a motorcycle in the garage, badly, since 2019.', ['vinyl', 'boardgames', 'neighbors']),
  P('Zara', false, 30, 'oakland', 164, true, [], true, 'Journalist covering housing. I ask too many questions, it is a professional condition.', ['film', 'bookclub', 'volunteers']),
  P('Vincent', true, 34, 'mountainview', 180, false, [], true, 'Compiler engineer. Trail running, board games, and an espresso setup that has got out of hand.', ['trailrunners', 'boardgames', 'chess']),
  P('Delia', false, 43, 'willowglen', 166, false, [16, 13], true, 'Speech therapist. Two teenagers, a garden plot and a book club that keeps me honest.', ['garden', 'bookclub', 'newparents']),
  P('Omar', true, 29, 'santaclara', 174, false, [], true, 'Network engineer. Surfing at dawn, climbing at night, sleeping on the train.', ['surf', 'climbing', 'trailrunners']),
  P('Petra', false, 48, 'sunset', 172, false, [22], false, 'Ceramicist with a studio in the Bayview. My work is slow and I like it that way.', ['photowalks', 'jazz', 'farmers']),
  P('Louis', true, 57, 'menlopark', 184, false, [29, 26], false, 'Retired airline pilot. Cycling, wine and a standing tee time I never keep.', ['cycling', 'wine', 'alumni']),
  P('Freya', false, 26, 'berkeley', 161, false, [], true, 'PhD student in neuroscience. Climbing partner, jazz enthusiast, chronic overcommitter.', ['climbing', 'jazz', 'bookclub']),
  P('Malik', true, 36, 'citycenter', 188, false, [7], false, 'Public defender. My son and I hike every other weekend and he sets the pace now.', ['marin', 'volunteers', 'newparents']),
  P('Sana', false, 33, 'fostercity', 157, false, [], true, 'Cloud architect. Swim, work, garden, repeat. I like a routine and I am not sorry.', ['swimmers', 'garden', 'yoga']),
  P('Theo', true, 24, 'downtownsj', 179, true, [], true, 'Apprentice sound engineer. Records, gigs, and a bike with no working brakes, which I am fixing.', ['jazz', 'vinyl', 'cycling']),
  P('Renata', false, 41, 'cupertino', 168, false, [11, 9], false, 'Systems engineer. Neighbourhood organiser by accident, board game host by choice.', ['neighbors', 'boardgames', 'newparents']),
  P('Sebastian', true, 47, 'applepark', 182, false, [17], false, 'Silicon design manager. Long rides on Saturdays, chess on Tuesdays, teenager the rest of the time.', ['cycling', 'chess', 'alumni']),
  P('Nadia', false, 32, 'soma', 165, false, [], true, 'Startup operations lead. Founders coffee, film club, and a running streak I am oddly proud of.', ['founders', 'film', 'trailrunners']),
  P('Colin', true, 38, 'redwoodshores', 176, true, [12], true, 'Sales engineer. Divorced, co parenting, and rediscovering the surf I gave up at twenty five.', ['surf', 'wine', 'volunteers']),
  P('Amelie', false, 28, 'paloalto', 170, false, [], true, 'Interaction designer. Photo walks, yoga at the baylands, and an unhealthy relationship with fresh bread.', ['photowalks', 'yoga', 'farmers']),
  P('Hector', true, 50, 'milpitas', 181, false, [23, 20], false, 'Machinist. Two grown kids, a workshop, and a long list of things the neighbours need welded.', ['neighbors', 'vinyl', 'volunteers']),
  P('Wren', false, 34, 'noevalley', 159, false, [], false, 'Sound designer for games. I hear everything, which is a blessing at work and a curse on the bus.', ['film', 'jazz', 'boardgames']),
  P('Bruno', true, 42, 'oakland', 187, false, [14, 10], false, 'Contractor. I build for a living and hike to stop thinking about building.', ['marin', 'neighbors', 'cycling']),
  P('Iris', false, 55, 'losgatos', 163, false, [27], false, 'Estate lawyer. Wine club, garden plot, and a daughter who calls every Sunday.', ['wine', 'garden', 'bookclub']),
  P('Nikhil', true, 31, 'googleplex', 175, false, [], true, 'Search engineer. Climbing, chess and a stubborn attempt to learn the double bass.', ['climbing', 'chess', 'jazz']),
  P('Cleo', false, 37, 'mission', 167, true, [6], true, 'Tattoo artist. Single mother, market regular, and the person who knows where the good coffee is.', ['farmers', 'vinyl', 'newparents']),
  P('Lars', true, 45, 'sunnyvale', 185, false, [19, 16], false, 'Firmware engineer. Two teenagers, a garage of bicycles, and a trail habit that started as physio.', ['trailrunners', 'cycling', 'neighbors']),
  P('Vera', false, 39, 'sanmateo', 169, false, [], false, 'Restaurant owner. Six days a week, and on the seventh I swim and say nothing to anybody.', ['swimmers', 'wine', 'farmers']),
  P('Idris', true, 26, 'berkeley', 178, false, [], true, 'Grad student in economics. Board games, book club, and a bike that has crossed the bridge too many times.', ['boardgames', 'bookclub', 'cycling']),
  P('Margot', false, 49, 'menlopark', 162, false, [21, 18], false, 'Clinical psychologist. Hiking Marin, reading everything, and learning to leave work at work.', ['marin', 'bookclub', 'yoga']),
  P('Pablo', true, 30, 'missionbay', 180, false, [], true, 'Bioinformatics engineer. Surf when I can, film club when I cannot.', ['surf', 'film', 'climbing']),
  P('Gita', false, 44, 'fremont', 158, false, [15, 12], true, 'Civil engineer. Two kids, a garden plot and a Sunday market ritual nobody in this family may skip.', ['garden', 'farmers', 'newparents']),
  P('Anton', true, 58, 'findistrict', 183, true, [31, 28], false, 'Retired banker. Jazz, wine and the long way home along the waterfront.', ['jazz', 'wine', 'volunteers']),
  P('Rosalind', false, 25, 'mountainview', 173, false, [], true, 'Junior architect. Photo walks, climbing gym, and a sketchbook I never finish.', ['photowalks', 'climbing', 'yoga']),
  P('Elias', true, 41, 'campbell', 177, false, [8, 5], false, 'Data engineer. Two small children, a chess set they keep losing pieces from, and a bike trailer.', ['chess', 'newparents', 'cycling']),
  P('Suri', false, 36, 'santaclara', 166, false, [], true, 'Hardware program manager. Trail runs at sunrise, book club at night, market in between.', ['trailrunners', 'bookclub', 'farmers']),
  P('Joaquin', true, 53, 'willowglen', 184, false, [24, 21], false, 'School principal. Thirty years of other people’s teenagers, and two of my own, now grown.', ['volunteers', 'neighbors', 'wine']),
  P('Edith', false, 47, 'alameda', 160, false, [20], false, 'Marine engineer. I fix boats, I sail badly, and I swim better than both.', ['swimmers', 'surf', 'marin']),
  P('Rami', true, 27, 'moffett', 179, true, [], true, 'Avionics technician. Records, jazz nights and a motorcycle I promise is safe.', ['vinyl', 'jazz', 'boardgames']),
  P('Lena', false, 40, 'cupertino', 171, false, [13, 10], false, 'Test lead. Neighbourhood potlucks, garden plot, two kids who eat everything I grow.', ['neighbors', 'garden', 'newparents']),
  P('Casper', true, 35, 'researchpark', 186, false, [], true, 'Optics engineer. Climbing, film club and a long standing plan to walk from here to Santa Cruz.', ['climbing', 'film', 'marin']),
  P('Alma', false, 51, 'sunset', 164, true, [25, 23], false, 'Costume designer. Two grown children, a house full of fabric and a jazz habit older than they are.', ['jazz', 'film', 'photowalks']),
  P('Tobias', true, 32, 'soma', 174, false, [], true, 'Security engineer. Founders coffee for the company, trail running for everything else.', ['founders', 'trailrunners', 'chess']),
  P('Ines', false, 29, 'redwoodcity', 168, false, [], true, 'Occupational therapist. Yoga, swimming, and a standing Saturday at the volunteer kitchen.', ['yoga', 'swimmers', 'volunteers']),
  P('Gordon', true, 62, 'paloalto', 180, false, [34, 31], false, 'Emeritus professor of geology. I still walk the coast every week and I still take samples.', ['marin', 'alumni', 'garden']),
  P('Noor', false, 33, 'downtownsj', 161, false, [], true, 'Civil rights attorney. Books, films and the kind of arguments that last past midnight.', ['bookclub', 'film', 'volunteers']),
  P('Silas', true, 39, 'oakland', 182, false, [11], true, 'Music teacher. My daughter plays better than I did at her age, which is the whole point.', ['jazz', 'vinyl', 'newparents']),
  P('Ophelia', false, 42, 'fostercity', 165, false, [17, 14], false, 'Air traffic controller. Precise at work, disorganised everywhere else. Two teenagers keep the balance.', ['swimmers', 'boardgames', 'neighbors']),
]
